In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [2]:
data= load_iris()

In [3]:
df= pd.DataFrame(data.data, columns=data.feature_names)

In [4]:
df.shape

(150, 4)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
df['target']=data.target

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
X= df.drop(['target'], axis =1)
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
y= df.target
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [12]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
X_train.shape

(100, 4)

In [14]:
X_test.shape

(50, 4)

In [15]:
model= SVC()
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
# orginal parameters passed
cross_val_score(SVC(C=1.0, kernel='rbf', gamma='scale'), X ,y ,cv=3)

array([0.96, 0.98, 0.94])

In [18]:
cross_val_score(SVC(C=10.0, kernel='rbf'), X ,y ,cv=3)

array([0.98, 1.  , 0.94])

In [19]:
# hyperparameter tunning in parameter
cross_val_score(SVC(C=10, kernel='poly', degree=2), X ,y ,cv=3)

array([0.98, 0.94, 0.98])

In [20]:
kval= ['rbf','linear']
cval=[1,10,20]

In [21]:
for i in kval:
    for j in cval:
        cross_val_score(SVC(C=j, kernel=i, gamma='scale'), X ,y ,cv=3)
        

NameError: name 'kaval' is not defined