In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

In [25]:
digits= load_digits()

In [26]:
 X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=0.33, random_state=42)

In [27]:
X_train.shape

(1203, 64)

In [28]:
X_test.shape

(594, 64)

# check score using diff algorithm

In [29]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [30]:
sv = SVC()
sv.fit(X_train,y_train)
sv.score(X_test,y_test)

0.9865319865319865

In [31]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9797979797979798

# function for using multiple algo

In [32]:
def get_score(model, X_train,y_train,X_test,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [33]:
get_score(lr,X_train,y_train,X_test,y_test)

C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

# K- Fold

In [34]:
from sklearn.model_selection import KFold

In [35]:
fold= KFold()

In [36]:
l =[1,2,3,4,5,6,7,8,9]

# if value of n-split is 3

1st split =[1,2,3,] - testing
         
          =[4,5,6,7,8,9] - training
          
2nd split = [4,5,6] - testing
         
          = [1,2,3,7,8,9]- training
         
3rd split = [7,8,9] - testing
          
          = [1,2,3,4,5,6] - training

In [37]:
fold= KFold(n_splits=3)

In [38]:
fold.split(l)

<generator object _BaseKFold.split at 0x00000222594FAF80>

In [39]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
for train_index,test_index in fold.split(l):
    print (train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# Stratifiedfold

In [41]:
from sklearn.model_selection import StratifiedKFold

In [46]:
kf= StratifiedKFold(n_splits=3)

In [43]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:

l1 = [0,0,0,1,1,1,2,2,2]
l1

[0, 0, 0, 1, 1, 1, 2, 2, 2]

In [47]:
for train_index,test_index in kf.split(l,l1):
    print (train_index,test_index)

[1 2 4 5 7 8] [0 3 6]
[0 2 3 5 6 8] [1 4 7]
[0 1 3 4 6 7] [2 5 8]


In [48]:
lr_score=[]
SVM_score=[]
rf_score=[] 

In [65]:
# find accuracy using stratifiedfold of these algo.
lr_score=[]
SVM_score=[]
rf_score=[]

# use for loop to run all together
# kf.split will provide train_index and text_index

for train_index,test_index in kf.split(digits.data,digits.target):
#     print (train_index,test_index)
   
# we want original values therefore use digits.data[train index] 
# this will provide value  on that index 
    X_train,X_test = digits.data[train_index],digits.data[test_index]
    y_train,y_test = digits.target[train_index],digits.target[test_index]
    
# append the accuracy into the list
# call the function
# the passs the train and test values in it

    
    lr_score.append(get_score(lr,X_train,y_train,X_test,y_test))
    SVM_score.append(get_score(sv,X_train,y_train,X_test,y_test))
    rf_score.append(get_score(rf,X_train,y_train,X_test,y_test))

C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [50]:
lr_score

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [51]:
SVM_score

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [52]:
rf_score

[0.9398998330550918, 0.9616026711185309, 0.9248747913188647]

# find mean to find perfect accuracy

In [53]:
np.mean(lr_score)

0.9265442404006677

In [54]:
np.mean(SVM_score)

0.9699499165275459

In [55]:
np.mean(rf_score)

0.9421257651641625

# cross validation score

In [56]:
from sklearn.model_selection import cross_val_score

In [57]:
cross_val_score(LogisticRegression(max_iter=7600),digits.data,digits.target,cv=5)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [58]:
cross_val_score(SVC(),digits.data,digits.target,cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [59]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=5)

array([0.92777778, 0.9       , 0.96100279, 0.96100279, 0.92200557])

# hyperparmeter tunning for SVC

In [72]:
cross_val_score(SVC(kernel='sigmoid'),digits.data,digits.target,cv=3)

array([0.86978297, 0.90651085, 0.87646077])

In [73]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=5)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])

In [77]:
cross_val_score(SVC(C=10),digits.data,digits.target,cv=3)

array([0.96828047, 0.97996661, 0.97328881])